### ISSUE TITLE
MariaDB did not start

### ISSUE THREAD

**Issue by Tazovsky** [giovtorres/docker-centos7-slurm#14]
I tried to run container with following `docker-compose.yml`:

```
version: '3'

services:
  slurm:
    image: giovtorres/docker-centos7-slurm:latest
    build: .
    hostname: ernie
    stdin_open: true
    tty: true
    volumes:
      - ./volumes/lib:/var/lib/slurmd
      - ./volumes/spool:/var/spool/slurmd
      - ./volumes/log:/var/log/slurm
      - ./volumes/db:/var/lib/mysql
```

but it fails on starting MariaDB:

```shell
$ docker-compose up
Creating docker-centos7-slurm_slurm_1 ... done
Attaching to docker-centos7-slurm_slurm_1
slurm_1  | - Initializing database
slurm_1  | - Database initialized
slurm_1  | - Updating MySQL directory permissions
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | 191017 08:41:46 mysqld_safe Logging to '/var/log/mariadb/mariadb.log'.
slurm_1  | 191017 08:41:46 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | - Starting MariaDB to create Slurm account database
slurm_1  | MariaDB did not start
docker-centos7-slurm_slurm_1 exited with code 1
```

Did I miss something?
